import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify"; // Import ToastContainer
import UserProvider from "@/context/UserProvider";
import Navbar from "@/components/Navbar";
import MainPage from "@/components/MainPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Navbar />
          <div className="bg-black"> {children}</div>
          <MainPage />
          <ToastContainer />{" "}
          {/* ToastContainer is now imported and used here */}
        </UserProvider>
      </body>
    </html>
  );
}
